---
abstract: 'Steroids for your perl one-liners.'
author:
  - 'Naveed Massjouni <naveedm9@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-p
requires:
  Data::Dump: 0
  File::Slurp: 0
  JSON::XS: 0
  L: 0
  LWP::Simple: 0
  List::AllUtils: 0
  Pod::Usage: 0
  Scalar::Util: 0
  XML::Hash::LX: 0
  YAML::XS: 0
  utf8::all: 0
resources:
  bugtracker: http://github.com/ironcamel/App-p/issues
  repository: git://github.com/ironcamel/App-p.git
version: 0.0304
